export const ANIME_IMAGES = [
  "/images/animate_images/1.png",
  "/images/animate_images/2.png",
  "/images/animate_images/3.png",
  "/images/animate_images/4.png",
  "/images/animate_images/5.png",
  "/images/animate_images/6.png",
  "/images/animate_images/7.png",
  "/images/animate_images/8.png",
  "/images/animate_images/11.png",
  "/images/animate_images/12.png",
  "/images/animate_images/13.png",
  "/images/animate_images/14.png",
  "/images/animate_images/18.png",
  "/images/animate_images/19.png",
  "/images/animate_images/adesivos.png",
  "/images/animate_images/camera.png",
  "/images/animate_images/download (9).png",
  "/images/animate_images/download (10).png",
  "/images/animate_images/download (11).png",
  "/images/animate_images/download (12).png",
  "/images/animate_images/download (13).png",
  "/images/animate_images/download (14).png",
  "/images/animate_images/download (15).png",
  "/images/animate_images/download (16).png",
  "/images/animate_images/download (17).png",
  "/images/animate_images/download (18).png",
  "/images/animate_images/download (19).png",
  "/images/animate_images/download (20).png",
  "/images/animate_images/download (21).png",
  "/images/animate_images/download (22).png",
  "/images/animate_images/download (23).png",
];
